{{- $hasAny := or .Values.secrets.userlistFile .Values.secrets.tlsClientCert .Values.secrets.tlsClientKey .Values.secrets.tlsClientCA .Values.secrets.adminToken -}}
{{- if $hasAny }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgrouter.fullname" . }}-secrets
  labels:
    {{- include "pgrouter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.userlistFile }}
  userlist.txt: {{ .Values.secrets.userlistFile | b64enc }}
  {{- end }}
  {{- if .Values.secrets.tlsClientCert }}
  tls.crt: {{ .Values.secrets.tlsClientCert | b64enc }}
  {{- end }}
  {{- if .Values.secrets.tlsClientKey }}
  tls.key: {{ .Values.secrets.tlsClientKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.tlsClientCA }}
  ca.crt: {{ .Values.secrets.tlsClientCA | b64enc }}
  {{- end }}
  {{- if .Values.secrets.adminToken }}
  admin_token: {{ .Values.secrets.adminToken | b64enc }}
  {{- end }}
{{- end }}
